version: '3.1'

services:

  fcrepo:
    build:
      context: ./fcrepo
    image: slarx/fcrepo:latest
    container_name: fcrepo
    ports:
      - "${JETTY_PORT}:${JETTY_PORT}"
    volumes:
      - slarxdata:/data
    depends_on:
      - assets

  assets:
    build:
      context: ./assets
    image: slarx/assets:latest
    container_name: assets
    volumes:
      - slarxdata:/data

volumes:

  slarxdata:
    driver: local

